from transformers import AutoTokenizer, AutoModelForSequenceClassification, pipeline

# Load pre-trained model and tokenizer (hypothetical model name)
model_name = "somebody/ai-text-detector"
model = AutoModelForSequenceClassification.from_pretrained(model_name)
tokenizer = AutoTokenizer.from_pretrained(model_name)

# Create a pipeline
ai_text_detector = pipeline("text-classification", model=model, tokenizer=tokenizer)

# Sample text
sample_text = "This is an example text generated by an AI."

# Detect AI-generated text
result = ai_text_detector(sample_text)
print(result)
